/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.ac.bolton;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Launcher classUnderTest = new Launcher();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
