/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.ac.bolton;

import java.util.ArrayList;
import java.util.List;
import uk.ac.bolton.view.ChannelForm;
import uk.ac.bolton.view.ISuperChannel;
import uk.ac.bolton.view.UserLoginForm;

public class Launcher {

    private static final List<ISuperChannel> channelList;

    static {
        channelList = new ArrayList<>();
        channelList.add(new ChannelForm());
    }
    
    private static void channelLauncher() {
        for (int i = 0; i < channelList.size(); i++) {
            System.out.println(i);
            channelList.get(i).displayForm(true);
        }
    }

    public static void main(String[] args) {

        channelLauncher();
       new UserLoginForm().setVisible(true);
    }
}
