/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.ac.bolton;

import uk.ac.bolton.view.ChannelForm;
import uk.ac.bolton.view.UserLoginForm;

public class Launcher {

    public static void main(String[] args) {
//        ChannelObservableeeee co = new ChannelObservableImpl();
//        new Dashboard(co).setVisible(true);
            
          new ChannelForm().setVisible(true);
          new UserLoginForm().setVisible(true);

    }
}
